questions = {
        'Which brawler deals less damage the farther it is?' : 'D',
        'How many brawlers are on the trophy road?' :'A',
        'Which of these skins does not exist?' : 'C',
        'Which brawler is given when connecting your account with Supercell ID?' : 'B',
        'How many total trophies are required to unlock Dynamike?' : 'A',
        'How much HP does a brawler gain after picking up one power cube?' : 'B',
        'How many trophies are required to reach Rank 35?' : 'C',
        "When was Brawl Star' global release?" : "D",
        "How long does it take for your health to begin regenerating after taking damage?" : 'A',
        'Which Brawler shares the same voice actress with Shelly?' : 'B',
        'How many bullets Colt shoot with his Super attack?': 'C',
        'In Boss Fight, when the boss robot turns red, which state it is in?' : 'D',
        'Which group of brawlers all have same movement speed?' : 'A',
        'Who was the first brawler added in 2019?' : 'B',
        'In Gem Grab, what is the max number of Gems available in a match?' : 'C',
        'Which attack/ability is NOT related to Darryl?' : 'D',
        'How many robotic brawlers are in the game?' : 'A',
        'Which of the following is NOT human?' : 'B',
        'Which brawlers were not NOT released at the same time?' : 'C',
        'What was the second Chromatic brawler released?': 'D',
        'Which brawler has the most skins?':'A',
        'Which trio is Byron in?' : 'B',
        'Which trio is Brock in?' : 'C',
        'Which trio is Leon in?' : 'D',
        'Which trio is Grom in?' : 'A',
        'Which gamemode once had a different name?' : 'B',
        'Which brawler can shoot the farthest?' : 'C',
        'Which brawler can absorb the most damage?': 'D',
        'Which brawler has the highest DPS per ammo potential?': 'C',
        'What class is Grom in?' : 'A',
        'What class is Darryl in?' : 'B',
        'What class is Stu in?' : 'C',
        'What class is Max in?' : 'D',
        'What class is Fang in?' : 'A',
        'What class is Tick in?' : 'A',
        'What class is Ash in?' : 'B',
        'What class is Crow in?' : 'C',
        'What class is Sandy in?' : 'D',
        'What was the first Brawl Ball map ever added?':'C',
        "Who says, 'I'm the boss of bosses?'": 'B',
        "Who says, ' '": 'D',
        'Which brawler has not receieved a balance change?': 'A',
        'Which team won the 2020 BS World Finals?':'B',
        'Pierced is a map of which gamemode?' : 'A',
        'Diagonal Alley is a map of which gamemode?' : 'B',
        'Electric Zone is a map of which gamemode?' : 'C',
        'Danger Zone is a map of which gamemode?' : 'D',
        'Deathcap Trap is a map of which gamemode?' : 'A',
        "What is the name of Meg's second star power?" : 'B',
        "What is the name of Mortis's second gadget?" : 'C',
        "What is the name of Fang's first star power?" : 'D',
        "What is the name of Amber's gadget?" : "A",
        "What is the name of Belle's gadget?" : "B",
        "What is the name of Sprout's first gadget?" : 'C',
        "What is the name of Primo's second gadget?" : 'D'
        
      }

options = [
        ['A. Grom', 'B. Stu', 'C. Piper', 'D. Leon'],
        ['A. 12', 'B. 11', 'C. 9', 'D. 8'],
        ['A. Serenade Poco', 'B. Popcorn Rico', 'C. Dragon Slayer Jessie', 'D. El Rey'],
        ['A. Shelley', 'B. Barley', 'C. Primo', 'D. Poco'],
        ['A. 2000', 'B. 1000', 'C. 3000', 'D. 4000'],
        ['A. 300', 'B. 400', 'C. 500', 'D. 600'],
        ['A. 1500', 'B. 1300', 'C. 1250', 'D. 1150'],
        ['A. June 2019', 'B. December 2017', 'C. June 2018', 'D. December 2018'],
        ['A. 3 seconds', 'B. 4 seconds', 'C. 2 seconds', 'D. 3.5 seconds'],
        ['A. Jessie', 'B. Emz', 'C. Nita', 'D. Rosa'],
        ['A. 8', 'B. 10', 'C. 12', 'D. 14'],
        ['A. Angry', 'B. God Mode', 'C. Enraged', 'D. Furious'],
        ['A. Tick, Tara, Bo', 'B. Nita, Bibi, Penny', 'C. Frank, Darryl, Stu', 'D. Spike, Shelly, Sandy'],
        ['A. Leon', 'B. Gene', 'C. Carl', 'D. Rosa'],
        ['A. 31', 'B. 27', 'C. 29', 'D. 30'],
        ['A. Double Deuce', 'B. Barrel Roll', 'C. Steel Hoops', 'D. Double Barrel'],
        ['A. 8', 'B. 7', 'C. 6', 'D. 5'],
        ['A. Griff', 'B. Poco', 'C. Mortis', 'D. Lou'],
        ['A. Bea and Max', 'B. Pam and Tara', 'C. Piper and Darryl', 'D. Penny and Frank'],
        ['A. Gale', 'B. Colette', 'C. Lou', 'D. Surge'],
        ['A. Mortis', 'B. Colt', 'C. Shelly', 'D. Crow'],
        ['A. Gift Shop', 'B. Townsfolk', 'C. Snowtel', 'D. Mystic Wanderers'],
        ['A. Shaman', 'B. Retropolis', 'C. Arcade', 'D. Wild West'],
        ['A. Junker Family', 'B. Superhero', 'C. Gem Miners', 'D. Shaman Tribe'],
        ['A. Fantasy', 'B. Gift Shop', 'C. Gem Miners', 'D. Starr Force'],
        ['A. Bounty', 'B. Gem Grab', 'C. Heist', 'D. Brawl Ball'],
        ['A. Rico, B. Brock, C. Squeak, D. Colt'],
        ['A. Primo', 'B. Frank', 'C. Rosa', 'D. Nani'],
        ['A. Colt', 'B. Darryl', 'C. Lola','D. 8-Bit'],
        ['A. Damage Dealer', 'B. Tank', 'C. Assassin','D. Support'],
        ['A. Tank', 'B. Hybrid', 'C. Assassin','D. Support'],
        ['A. Damage Dealer', 'B. Tank', 'C. Assassin','D. Support'],
        ['A. Damage Dealer', 'B. Tank', 'C. Assassin','D. Support'],
        ['A. Damage Dealer', 'B. Tank', 'C. Assassin','D. Support'],
        ['A. Damage Dealer', 'B. Tank', 'C. Assassin','D. Support'],
        ['A. Damage Dealer', 'B. Tank', 'C. Assassin','D. Support'],
        ['A. Damage Dealer', 'B. Tank', 'C. Assassin','D. Support'],
        ['A. Damage Dealer', 'B. Tank', 'C. Assassin','D. Support'],
        ['A. Triple Dribble', 'B. Pinhole Punt', 'C. Backyard Bowl','D. Center Field'],
        ['A. Bull', 'B. Crow', 'C. Bibi','D. Gale'],
        ['A. Gene', 'B. Tara', 'C. Mr. P','D. Spike'],
        ['A. Buzz', 'B. Lola', 'C. Meg','D. Penny'],
        ['A. INTZ', 'B. PSG', 'C. ZETA','D. SK Gaming'],
        ['A. Gem Grab', 'B. Heist', 'C. Bounty', 'D. Hot Zone'],
        ['A. Gem Grab', 'B. Heist', 'C. Bounty', 'D. Hot Zone'],
        ['A. Gem Grab', 'B. Heist', 'C. Bounty', 'D. Hot Zone'],
        ['A. Gem Grab', 'B. Heist', 'C. Bounty', 'D. Hot Zone'],
        ['A. Gem Grab', 'B. Heist', 'C. Bounty', 'D. Hot Zone'],
        ['A. Force Field', 'B. Heavy Metal', 'C. To the Max','D. Pocket Detonator'], 
        ['A. Creepy Harvest', 'B. Coiled Snake', 'C. Survival Shovel','D. Combo Spinner'],
        ['A. Corn-fu', 'B. Divine Soles', 'C. X-Factor','D. Fresh Kicks'],
        ['A. Fire Starters', 'B. Wild Flames', 'C. Dragons breath','D. Torch em!'],
        ['A. Bear Trap', 'B. Nest Egg', 'C. Grounded','D. Snare-a-Bear'],
        ['A. Fertilization', 'B. Grow Light', 'C. Garden Mulcher', 'D. Seed Bomb'],
        ['A. El Fuego', 'B. Meteor Rush', 'C. Suplex Supplement', 'D. Asteroid Belt']]
        
        


